#pragma once
#include <custom_types.h>
#include <defines.h>

extern LEVEL level0;
extern CVECTOR level0_BGc;
extern VECTOR level0_BKc;
extern MESH_ANIMS_TRACKS level0_modelCube_001_anims;
extern VANIM level0_modelCube_001_anim_KeyAction_003;
extern VANIM level0_modelCube_001_anim_KeyAction_001;
extern VANIM level0_modelCube_001_anim_KeyAction_002;
extern VANIM level0_modelCube_001_anim_KeyAction;
extern VANIM level0_modelCube_001_anim_KeyAction_004;
extern CAMPOS level0_camPos_Camera;
extern CAMPATH level0_camPath;
extern MATRIX level0_lgtmat;
extern MATRIX level0_cmat;
extern SVECTOR modelCube_mesh[];
extern SVECTOR level0_modelCube_normal[];
extern CVECTOR level0_modelCube_color[];
extern PRIM level0_modelCube_index[];
extern BODY  level0_modelCube_body;
extern TMESH level0_modelCube;
extern MESH level0_meshCube;
extern SVECTOR modelCube_001_mesh[];
extern SVECTOR level0_modelCube_001_normal[];
extern CVECTOR level0_modelCube_001_color[];
extern PRIM level0_modelCube_001_index[];
extern BODY  level0_modelCube_001_body;
extern TMESH level0_modelCube_001;
extern MESH level0_meshCube_001;
extern SVECTOR modelPlane_000_mesh[];
extern SVECTOR level0_modelPlane_000_normal[];
extern SVECTOR level0_modelPlane_000_uv[];
extern CVECTOR level0_modelPlane_000_color[];
extern PRIM level0_modelPlane_000_index[];
extern BODY  level0_modelPlane_000_body;
extern TMESH level0_modelPlane_000;
extern unsigned long _binary_TIM_woods_tim_start[];
extern unsigned long _binary_TIM_woods_tim_end[];
extern unsigned long _binary_TIM_woods_tim_length;
extern TIM_IMAGE level0_tim_woods;
extern MESH level0_meshPlane_000;
extern SVECTOR modelPlane_001_mesh[];
extern SVECTOR level0_modelPlane_001_normal[];
extern SVECTOR level0_modelPlane_001_uv[];
extern CVECTOR level0_modelPlane_001_color[];
extern PRIM level0_modelPlane_001_index[];
extern BODY  level0_modelPlane_001_body;
extern TMESH level0_modelPlane_001;
extern MESH level0_meshPlane_001;
extern SVECTOR modelPlane_002_mesh[];
extern SVECTOR level0_modelPlane_002_normal[];
extern SVECTOR level0_modelPlane_002_uv[];
extern CVECTOR level0_modelPlane_002_color[];
extern PRIM level0_modelPlane_002_index[];
extern BODY  level0_modelPlane_002_body;
extern TMESH level0_modelPlane_002;
extern MESH level0_meshPlane_002;
extern SVECTOR modelPlane_005_mesh[];
extern SVECTOR level0_modelPlane_005_normal[];
extern SVECTOR level0_modelPlane_005_uv[];
extern CVECTOR level0_modelPlane_005_color[];
extern PRIM level0_modelPlane_005_index[];
extern BODY  level0_modelPlane_005_body;
extern TMESH level0_modelPlane_005;
extern MESH level0_meshPlane_005;
extern SVECTOR modelPlane_006_mesh[];
extern SVECTOR level0_modelPlane_006_normal[];
extern SVECTOR level0_modelPlane_006_uv[];
extern CVECTOR level0_modelPlane_006_color[];
extern PRIM level0_modelPlane_006_index[];
extern BODY  level0_modelPlane_006_body;
extern TMESH level0_modelPlane_006;
extern MESH level0_meshPlane_006;
extern MESH * level0_meshes[7];
extern int level0_meshes_length;
extern CAMANGLE level0_camAngle_Camera;
extern CAMANGLE * level0_camAngles[0];
extern SIBLINGS level0_nodePlane_siblings;
extern CHILDREN level0_nodePlane_objects;
extern CHILDREN level0_nodePlane_rigidbodies;
extern NODE level0_nodePlane;
extern MESH * level0_actorPtr;
extern MESH * level0_levelPtr;
extern MESH * level0_propPtr;
extern CAMANGLE * level0_camPtr;
extern NODE * level0_curNode;
extern VAGbank level0_VAGBank;
extern XAbank level0_XABank_0;
extern XAfiles level0_XAFiles;
extern SOUND_OBJECT level0_Speaker;
extern SOUND_OBJECT level0_Speaker_001;
extern SOUND_OBJECT level0_Speaker_003;
extern SOUND_OBJECT level0_Speaker_004;
extern SOUND_OBJECT level0_Speaker_005;
extern SOUND_OBJECT level0_Speaker_006;
extern SOUND_OBJECT level0_Speaker_007;
extern SOUND_OBJECT level0_Speaker_008;
extern SOUND_OBJECT level0_Speaker_009;
extern SOUND_OBJECT level0_Speaker_010;
extern LEVEL_SOUNDS level0_sounds;
extern NODE level0_nodePlane;
