#pragma once
#include <custom_types.h>
#include <defines.h>

extern LEVEL level1;
extern CVECTOR level1_BGc;
extern VECTOR level1_BKc;
extern MESH_ANIMS_TRACKS level1_modelCube_anims;
extern VANIM level1_modelCube_anim_Cube;
extern MESH_ANIMS_TRACKS level1_modelCylindre_anims;
extern VANIM level1_modelCylindre_anim_Cylindre;
extern CAMPOS level1_camPos_camPath;
extern CAMPOS level1_camPos_camPath_001;
extern CAMPOS level1_camPos_camPath_002;
extern CAMPOS level1_camPos_camPath_003;
extern CAMPOS level1_camPos_camPath_004;
extern CAMPOS level1_camPos_camPath_005;
extern CAMPATH level1_camPath;
extern MATRIX level1_lgtmat;
extern MATRIX level1_cmat;
extern SVECTOR modelCube_mesh[];
extern SVECTOR level1_modelCube_normal[];
extern SVECTOR level1_modelCube_uv[];
extern CVECTOR level1_modelCube_color[];
extern PRIM level1_modelCube_index[];
extern BODY  level1_modelCube_body;
extern TMESH level1_modelCube;
extern unsigned long _binary_TIM_cat_tim_start[];
extern unsigned long _binary_TIM_cat_tim_end[];
extern unsigned long _binary_TIM_cat_tim_length;
extern TIM_IMAGE level1_tim_cat;
extern MESH level1_meshCube;
extern SVECTOR modelCylindre_mesh[];
extern SVECTOR level1_modelCylindre_normal[];
extern SVECTOR level1_modelCylindre_uv[];
extern CVECTOR level1_modelCylindre_color[];
extern PRIM level1_modelCylindre_index[];
extern BODY  level1_modelCylindre_body;
extern TMESH level1_modelCylindre;
extern unsigned long _binary_TIM_home_tim_start[];
extern unsigned long _binary_TIM_home_tim_end[];
extern unsigned long _binary_TIM_home_tim_length;
extern TIM_IMAGE level1_tim_home;
extern MESH level1_meshCylindre;
extern SVECTOR modelgnd_mesh[];
extern SVECTOR level1_modelgnd_normal[];
extern SVECTOR level1_modelgnd_uv[];
extern CVECTOR level1_modelgnd_color[];
extern PRIM level1_modelgnd_index[];
extern BODY  level1_modelgnd_body;
extern TMESH level1_modelgnd;
extern MESH level1_meshgnd;
extern SVECTOR modelgnd_001_mesh[];
extern SVECTOR level1_modelgnd_001_normal[];
extern SVECTOR level1_modelgnd_001_uv[];
extern CVECTOR level1_modelgnd_001_color[];
extern PRIM level1_modelgnd_001_index[];
extern BODY  level1_modelgnd_001_body;
extern TMESH level1_modelgnd_001;
extern MESH level1_meshgnd_001;
extern SVECTOR modelgnd_003_mesh[];
extern SVECTOR level1_modelgnd_003_normal[];
extern SVECTOR level1_modelgnd_003_uv[];
extern CVECTOR level1_modelgnd_003_color[];
extern PRIM level1_modelgnd_003_index[];
extern BODY  level1_modelgnd_003_body;
extern TMESH level1_modelgnd_003;
extern MESH level1_meshgnd_003;
extern SVECTOR modelgnd_002_mesh[];
extern SVECTOR level1_modelgnd_002_normal[];
extern SVECTOR level1_modelgnd_002_uv[];
extern CVECTOR level1_modelgnd_002_color[];
extern PRIM level1_modelgnd_002_index[];
extern BODY  level1_modelgnd_002_body;
extern TMESH level1_modelgnd_002;
extern MESH level1_meshgnd_002;
extern SVECTOR modelLara_mesh[];
extern SVECTOR level1_modelLara_normal[];
extern SVECTOR level1_modelLara_uv[];
extern CVECTOR level1_modelLara_color[];
extern PRIM level1_modelLara_index[];
extern BODY  level1_modelLara_body;
extern TMESH level1_modelLara;
extern unsigned long _binary_TIM_lara_tim_start[];
extern unsigned long _binary_TIM_lara_tim_end[];
extern unsigned long _binary_TIM_lara_tim_length;
extern TIM_IMAGE level1_tim_lara;
extern MESH level1_meshLara;
extern SVECTOR modelobject_mesh[];
extern SVECTOR level1_modelobject_normal[];
extern SVECTOR level1_modelobject_uv[];
extern CVECTOR level1_modelobject_color[];
extern PRIM level1_modelobject_index[];
extern BODY  level1_modelobject_body;
extern TMESH level1_modelobject;
extern MESH level1_meshobject;
extern SVECTOR modelPlan_mesh[];
extern SVECTOR level1_modelPlan_normal[];
extern SVECTOR level1_modelPlan_uv[];
extern CVECTOR level1_modelPlan_color[];
extern PRIM level1_modelPlan_index[];
extern BODY  level1_modelPlan_body;
extern TMESH level1_modelPlan;
extern MESH level1_meshPlan;
extern SVECTOR modelSphere_mesh[];
extern SVECTOR level1_modelSphere_normal[];
extern SVECTOR level1_modelSphere_uv[];
extern CVECTOR level1_modelSphere_color[];
extern PRIM level1_modelSphere_index[];
extern BODY  level1_modelSphere_body;
extern TMESH level1_modelSphere;
extern MESH level1_meshSphere;
extern SVECTOR modelSphere_001_mesh[];
extern SVECTOR level1_modelSphere_001_normal[];
extern SVECTOR level1_modelSphere_001_uv[];
extern CVECTOR level1_modelSphere_001_color[];
extern PRIM level1_modelSphere_001_index[];
extern BODY  level1_modelSphere_001_body;
extern TMESH level1_modelSphere_001;
extern MESH level1_meshSphere_001;
extern SVECTOR modelwall_mesh[];
extern SVECTOR level1_modelwall_normal[];
extern SVECTOR level1_modelwall_uv[];
extern CVECTOR level1_modelwall_color[];
extern PRIM level1_modelwall_index[];
extern BODY  level1_modelwall_body;
extern TMESH level1_modelwall;
extern MESH level1_meshwall;
extern SVECTOR modelwall_001_mesh[];
extern SVECTOR level1_modelwall_001_normal[];
extern SVECTOR level1_modelwall_001_uv[];
extern CVECTOR level1_modelwall_001_color[];
extern PRIM level1_modelwall_001_index[];
extern BODY  level1_modelwall_001_body;
extern TMESH level1_modelwall_001;
extern MESH level1_meshwall_001;
extern SVECTOR modelwall_002_mesh[];
extern SVECTOR level1_modelwall_002_normal[];
extern SVECTOR level1_modelwall_002_uv[];
extern CVECTOR level1_modelwall_002_color[];
extern PRIM level1_modelwall_002_index[];
extern BODY  level1_modelwall_002_body;
extern TMESH level1_modelwall_002;
extern MESH level1_meshwall_002;
extern SVECTOR modelwall_003_mesh[];
extern SVECTOR level1_modelwall_003_normal[];
extern SVECTOR level1_modelwall_003_uv[];
extern CVECTOR level1_modelwall_003_color[];
extern PRIM level1_modelwall_003_index[];
extern BODY  level1_modelwall_003_body;
extern TMESH level1_modelwall_003;
extern MESH level1_meshwall_003;
extern MESH * level1_meshes[15];
extern int level1_meshes_length;
extern CAMANGLE level1_camAngle_camPath_001;
extern CAMANGLE * level1_camAngles[0];
extern SIBLINGS level1_nodegnd_siblings;
extern CHILDREN level1_nodegnd_objects;
extern CHILDREN level1_nodegnd_rigidbodies;
extern NODE level1_nodegnd;
extern SIBLINGS level1_nodegnd_002_siblings;
extern CHILDREN level1_nodegnd_002_objects;
extern CHILDREN level1_nodegnd_002_rigidbodies;
extern NODE level1_nodegnd_002;
extern SIBLINGS level1_nodegnd_001_siblings;
extern CHILDREN level1_nodegnd_001_objects;
extern CHILDREN level1_nodegnd_001_rigidbodies;
extern NODE level1_nodegnd_001;
extern SIBLINGS level1_nodegnd_003_siblings;
extern CHILDREN level1_nodegnd_003_objects;
extern CHILDREN level1_nodegnd_003_rigidbodies;
extern NODE level1_nodegnd_003;
extern MESH * level1_actorPtr;
extern MESH * level1_levelPtr;
extern MESH * level1_propPtr;
extern CAMANGLE * level1_camPtr;
extern NODE * level1_curNode;
extern NODE level1_nodegnd;
extern NODE level1_nodegnd_002;
extern NODE level1_nodegnd_001;
extern NODE level1_nodegnd_003;
