name: Windows build
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch submodules
      run: git submodule update --init --recursive
    - name: Set script
      run: |
        powershell -c "& { iwr https://raw.githubusercontent.com/grumpycoders/pcsx-redux/main/mips.ps1 | iex }"
        echo "$env:GITHUB_WORKSPACE/mips" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "$env:GITHUB_WORKSPACE/mips/mips/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Install toolchain
      run: |
        mips install 11.2.0
        C:\msys64\usr\bin\wget.exe https://github.com/Lameguy64/mkpsxiso/releases/download/v1.26/mkpsxiso-1.26.zip
        7z.exe x mkpsxiso-1.20.zip -o"$GITHUB_WORKSPACE\mkpsxiso"
        echo "$env:GITHUB_WORKSPACE/mkpsxiso" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        C:\msys64\usr\bin\wget.exe http://psx.arthus.net/sdk/Psy-Q/psyq-4.7-converted-full.7z
        7z.exe x psyq-4.7-converted-full.7z -o"$GITHUB_WORKSPACE\nolibgs_hello_worlds\psyq"
        
    - name: Make all
      run: make all
